name = "Dynesty"
uuid = "eb527566-0f3e-4aab-bb5f-9d2e403dba70"
authors = ["Paul Tiede <ptiede91@gmail.com> and contributors"]
version = "0.3.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CondaPkg = "0.2"
PythonCall = "0.9"
StatsBase = "0.32, 0.33, 0.34"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
