name = "Dynesty"
uuid = "eb527566-0f3e-4aab-bb5f-9d2e403dba70"
authors = ["Paul Tiede <ptiede91@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
PyCall = "1"
StatsBase = "0.32, 0.33"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
